### ISSUE TITLE
Readme - nuget info

### ISSUE THREAD

**Issue by tinohager** [J0rgeSerran0/JsonNamingPolicy#1]
Can you add a backlink to nuget?

### nuget
The package is available via [nuget](https://www.nuget.org/packages/JorgeSerrano.Json.JsonSnakeCaseNamingPolicy)
```
PM> install-package JorgeSerrano.Json.JsonSnakeCaseNamingPolicy
```

**Comment by J0rgeSerran0** [comment]
Hi @tinohager 
Thank you very much for the info and sorry for the delay.
I had planned to publish a nuget package about these conventions, but when I found this package, I decided does not publish it.
Duplicate the same is not a good idea.
I am going to change the readme file to inform about it and close this.
Thanks a lot!

**Comment by tinohager** [comment]
Hi @J0rgeSerran0 

I take a very critical view when someone publishes a package in their name. I can't rely on the code from their repository being in the package.

**Comment by J0rgeSerran0** [comment]
Hi @tinohager 
So, and I guess, that your suggestion is that I could publish a NuGet Package with the code to be comfortable with it.
And in this case doesn't matter if the code is duplicated, the important point here is that the publisher should be me, isn't it?.
